from __future__ import annotations

import io
import logging

import json as json_mod

import httpx
from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.adapters.ai import get_ai_adapter, OpenAICompatibleAdapter, StubAIAdapter
from app.api.deps import get_db
from app.schemas.ai import (
    ExtractTextResponse,
    InferOfferKnowledgeRequest,
    InferOfferKnowledgeResponse,
    InferredKnowledgeItem,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/ai", tags=["ai"])


@router.get("/status")
async def ai_status(db: AsyncSession = Depends(get_db)):
    """Check whether a real LLM is configured and ready."""
    adapter = await get_ai_adapter(db, scene_key="knowledge")
    ready = not isinstance(adapter, StubAIAdapter)
    info = {}
    if isinstance(adapter, OpenAICompatibleAdapter):
        info = {"provider": adapter.provider, "model": adapter.model}
    return {"ready": ready, **info}


def _build_offer_data(body: InferOfferKnowledgeRequest) -> dict:
    """Build offer_data dict from request. Shared by stream and non-stream endpoints."""
    knowledge_items = []
    if body.existing_knowledge:
        knowledge_items = [
            {"knowledge_type": k.knowledge_type, "title": k.title, "content_raw": k.content_raw}
            for k in body.existing_knowledge
        ]
    return {
        "offer": {"name": body.name, "offer_type": body.offer_type, "description": body.description},
        "selling_points": [], "target_audiences": [], "target_scenarios": [],
        "knowledge_items": knowledge_items,
    }


def _build_suggestions(raw: dict) -> dict[str, list[InferredKnowledgeItem]]:
    suggestions = {}
    for category, items in raw.items():
        suggestions[category] = [
            InferredKnowledgeItem(
                knowledge_type=category,
                title=item.get("title", ""),
                content_raw=item.get("content_raw", ""),
                confidence=item.get("confidence", 0.0),
            )
            for item in items
        ]
    return suggestions


@router.post("/infer-offer-knowledge", response_model=InferOfferKnowledgeResponse)
async def infer_offer_knowledge(body: InferOfferKnowledgeRequest, db: AsyncSession = Depends(get_db)):
    """Infer knowledge from offer info. Works for both creation (no existing) and update (with existing)."""
    offer_data = _build_offer_data(body)

    adapter = await get_ai_adapter(db, scene_key="knowledge")
    if isinstance(adapter, StubAIAdapter):
        raise HTTPException(
            status_code=503,
            detail="NO_LLM_CONFIGURED",
        )
    try:
        raw = await adapter.infer_knowledge(offer_data, body.language)
    except Exception as e:
        desc_len = len(body.description or "")
        logger.error(
            "infer-offer-knowledge failed | name=%s type=%s desc_len=%d lang=%s | %s",
            body.name, body.offer_type, desc_len, body.language, e,
            exc_info=True,
        )
        raise HTTPException(status_code=502, detail=f"LLM_CALL_FAILED: {e}")

    if not raw:
        logger.error("infer-offer-knowledge returned empty | name=%s type=%s desc_len=%d lang=%s",
                      body.name, body.offer_type, len(body.description or ""), body.language)
        raise HTTPException(status_code=502, detail="LLM returned empty response")

    # Extract description generated by LLM (if present), remove from raw before building suggestions
    description = raw.pop("description", None) if isinstance(raw, dict) else None

    return InferOfferKnowledgeResponse(
        offer_name=body.name,
        description=description,
        suggestions=_build_suggestions(raw),
    )


@router.post("/infer-offer-knowledge-stream")
async def infer_offer_knowledge_stream(body: InferOfferKnowledgeRequest, db: AsyncSession = Depends(get_db)):
    """Streaming version: sends SSE events with thinking text, then final result."""
    offer_data = _build_offer_data(body)

    adapter = await get_ai_adapter(db, scene_key="knowledge")
    if isinstance(adapter, StubAIAdapter):
        raise HTTPException(status_code=503, detail="NO_LLM_CONFIGURED")
    if not isinstance(adapter, OpenAICompatibleAdapter):
        raise HTTPException(status_code=501, detail="Streaming not supported for this adapter")

    async def event_stream():
        try:
            async for event_type, data in adapter.infer_knowledge_stream(offer_data, body.language):
                if event_type == "thinking":
                    yield f"data: {json_mod.dumps({'type': 'thinking', 'text': data}, ensure_ascii=False)}\n\n"
                elif event_type == "result":
                    description = data.pop("description", None) if isinstance(data, dict) else None
                    suggestions = {
                        cat: [item.model_dump() for item in items]
                        for cat, items in _build_suggestions(data).items()
                    }
                    result = {
                        "type": "result",
                        "offer_name": body.name,
                        "description": description,
                        "suggestions": suggestions,
                    }
                    yield f"data: {json_mod.dumps(result, ensure_ascii=False)}\n\n"
        except Exception as e:
            logger.error("infer-offer-knowledge-stream failed | name=%s | %s", body.name, e, exc_info=True)
            yield f"data: {json_mod.dumps({'type': 'error', 'detail': str(e)})}\n\n"

    return StreamingResponse(event_stream(), media_type="text/event-stream")


def _extract_pdf_text(content: bytes) -> str:
    from PyPDF2 import PdfReader
    reader = PdfReader(io.BytesIO(content))
    parts = []
    for page in reader.pages:
        text = page.extract_text()
        if text:
            parts.append(text)
    return "\n".join(parts)


def _strip_jina_metadata(text: str) -> str:
    """Strip Jina Reader metadata headers. Leave content as-is — LLM handles markdown fine."""
    import re
    text = re.sub(r"^(Title|URL Source|Published Time|Markdown Content):.*$", "", text, flags=re.MULTILINE)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


async def _extract_url_text(url: str) -> str:
    """Extract text from a URL using Jina Reader (handles JS-rendered SPA pages)."""
    import re
    jina_url = f"https://r.jina.ai/{url}"
    jina_error = None
    try:
        async with httpx.AsyncClient(follow_redirects=True, timeout=45) as client:
            resp = await client.get(jina_url, headers={"Accept": "text/plain"})
            resp.raise_for_status()
            text = _strip_jina_metadata(resp.text)
            if text:
                return text
    except Exception as e:
        jina_error = str(e)
        logger.warning("Jina Reader failed for %s: %s, falling back to direct fetch", url, jina_error)

    # Fallback: direct fetch + strip tags
    try:
        async with httpx.AsyncClient(follow_redirects=True, timeout=15) as client:
            resp = await client.get(url)
            resp.raise_for_status()
    except Exception as e:
        raise HTTPException(400, f"Unable to access URL: {e}")

    raw = resp.content.decode("utf-8", errors="ignore")
    text = re.sub(r"<script[^>]*>[\s\S]*?</script>", "", raw)
    text = re.sub(r"<style[^>]*>[\s\S]*?</style>", "", text)
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    # If extracted text is too short, the page likely requires JS rendering
    # and direct fetch only got an empty shell. Fail with a clear message.
    if len(text) < 200:
        raise HTTPException(
            400,
            "This page returned very little text content — it likely requires "
            "JavaScript to render. Please copy and paste the page content directly.",
        )

    # Detect code/script noise in extracted text (SPA frameworks leak inline JS)
    noise_chars = sum(1 for c in text if c in '{}();=>')
    noise_ratio = noise_chars / len(text) if text else 0
    if noise_ratio > 0.03:
        logger.warning("URL text has high code noise (%.1f%%): %s", noise_ratio * 100, url)
        raise HTTPException(
            400,
            "The extracted page content contains too much script/code noise — "
            "this site likely requires JavaScript to render properly. "
            "Please copy and paste the page content directly.",
        )

    return text


def _extract_docx_text(content: bytes) -> str:
    from docx import Document
    doc = Document(io.BytesIO(content))
    return "\n".join(p.text for p in doc.paragraphs if p.text.strip())


def _extract_excel_text(content: bytes) -> str:
    from openpyxl import load_workbook
    wb = load_workbook(io.BytesIO(content), read_only=True, data_only=True)
    lines = []
    for sheet in wb.worksheets:
        if len(wb.worksheets) > 1:
            lines.append(f"[{sheet.title}]")
        for row in sheet.iter_rows(values_only=True):
            cells = [str(c).strip() for c in row if c is not None]
            if cells:
                lines.append("\t".join(cells))
    wb.close()
    return "\n".join(lines)


@router.post("/extract-text", response_model=ExtractTextResponse)
async def extract_text(
    file: UploadFile | None = File(None),
    url: str | None = Form(None),
):
    """Extract text from a PDF/Word file or a URL."""
    if file and file.filename:
        content = await file.read()
        filename = file.filename.lower()

        if filename.endswith(".pdf"):
            text = _extract_pdf_text(content)
        elif filename.endswith((".docx", ".doc")):
            text = _extract_docx_text(content)
        elif filename.endswith((".xlsx", ".xls")):
            text = _extract_excel_text(content)
        elif filename.endswith((".txt", ".csv")):
            text = content.decode("utf-8", errors="ignore")
        else:
            raise HTTPException(400, f"Unsupported file format: {file.filename}. Supported: PDF, Word, Excel, CSV, TXT")

        if not text.strip():
            raise HTTPException(400, "Failed to extract text content from the file")

        return ExtractTextResponse(text=text.strip(), source="file", filename=file.filename)

    if url:
        # For PDF/Word URLs, fetch directly
        if url.lower().endswith((".pdf", ".docx", ".doc")):
            try:
                async with httpx.AsyncClient(follow_redirects=True, timeout=15) as client:
                    resp = await client.get(url)
                    resp.raise_for_status()
            except Exception as e:
                raise HTTPException(400, f"Unable to access URL: {e}")

            if url.lower().endswith(".pdf"):
                text = _extract_pdf_text(resp.content)
            else:
                text = _extract_docx_text(resp.content)
        else:
            # Use Jina Reader to handle JS-rendered pages (Vue/React/SPA)
            text = await _extract_url_text(url)

        if not text.strip():
            raise HTTPException(400, "Failed to extract text content from the URL")

        return ExtractTextResponse(text=text.strip()[:10000], source="url")

    raise HTTPException(400, "Please provide a file or URL")
